export { default as Can } from './components/Can.vue'
export { useAuthorization } from './composables/use-authorization'
export { can, canAll, canAny } from './permissions.utils'
export { AUTHORIZATION_KEY, authorizationQuery, PERMISSIONS_KEY, permissionsQuery } from './queries'
export { permissionRoutes } from './routes'
